###
POST http://localhost:8080/send
Content-Type: "application/json"

{
    "request_number":1500,
	"game":120,
	"gamename":"Juego Dos",
	"winner":"Javier",
	"players":200,
	"worker":""
}


###
GET http://localhost:8080/pubsub