version: "3.9"

services: 

  go:
    build: ./
    image: pubsub:subscriber
    container_name: sub
    ports:
      - "8090:8080"
    volumes:
      - .:/usr/src/goApp
    #command: bash -c "go mod init pubsub"
    #command: bash -c "go get github.com/gin-gonic/gin"
    #command: bash -c "go get github.com/joho/godotenv"
    #command: bash -c "go get cloud.google.com/go/pubsub"
    #command: bash -c "go get google.golang.org/api/option"
    #command: bash -c "go get golang.org/x/oauth2/google"
    #command: bash -c "go get github.com/go-redis/redis/v8"
    #command: bash -c "go get go.mongodb.org/mongo-driver/mongo/options"
    #command: bash -c "go get go.mongodb.org/mongo-driver/mongo"
  
    #env_file:
      #- ./GoApi/env.env
    #environment:
      #GOOGLE_APPLICATION_CREDENTALS: ./PK/PS_key.json
      #GIN_MODE: release          