version: "3.9"

services: 

  go:
    build: ./
    image: kafka:publisher
    #ports: 
    #  - "8080:8080"
    network_mode: "host"
    container_name: Kpub
    volumes:
      - .:/usr/src/goApp
    #command: bash -c "go mod init kafka"
    #command: bash -c "go get github.com/gin-gonic/gin"
    #command: bash -c "go get github.com/joho/godotenv"
    #command: bash -c "go get github.com/segmentio/kafka-go"
    #env_file:
      #- ./GoApi/env.env
    #environment:
      #GOOGLE_APPLICATION_CREDENTALS: ./PK/PS_key.json
      #GIN_MODE: release