// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SquidGameClient is the client API for SquidGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquidGameClient interface {
	// Sends a greeting
	StratGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameReply, error)
}

type squidGameClient struct {
	cc grpc.ClientConnInterface
}

func NewSquidGameClient(cc grpc.ClientConnInterface) SquidGameClient {
	return &squidGameClient{cc}
}

func (c *squidGameClient) StratGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*GameReply, error) {
	out := new(GameReply)
	err := c.cc.Invoke(ctx, "/proto.SquidGame/StratGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquidGameServer is the server API for SquidGame service.
// All implementations must embed UnimplementedSquidGameServer
// for forward compatibility
type SquidGameServer interface {
	// Sends a greeting
	StratGame(context.Context, *GameRequest) (*GameReply, error)
	mustEmbedUnimplementedSquidGameServer()
}

// UnimplementedSquidGameServer must be embedded to have forward compatible implementations.
type UnimplementedSquidGameServer struct {
}

func (UnimplementedSquidGameServer) StratGame(context.Context, *GameRequest) (*GameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StratGame not implemented")
}
func (UnimplementedSquidGameServer) mustEmbedUnimplementedSquidGameServer() {}

// UnsafeSquidGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquidGameServer will
// result in compilation errors.
type UnsafeSquidGameServer interface {
	mustEmbedUnimplementedSquidGameServer()
}

func RegisterSquidGameServer(s grpc.ServiceRegistrar, srv SquidGameServer) {
	s.RegisterService(&SquidGame_ServiceDesc, srv)
}

func _SquidGame_StratGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquidGameServer).StratGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SquidGame/StratGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquidGameServer).StratGame(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquidGame_ServiceDesc is the grpc.ServiceDesc for SquidGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquidGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SquidGame",
	HandlerType: (*SquidGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StratGame",
			Handler:    _SquidGame_StratGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game.proto",
}
