version: "3.9"

services: 

  go:
    build: ./
    image: gosubscriber1:latest
    container_name: sub
    ports:
      - "8090:8080"
    volumes:
      - .:/usr/src/goApp
    depends_on:
      - rabbitmq   

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    