version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "50051:50051"
    networks:
      - grpc

  client:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "2000:2000"
      networks:
        - grpc
      environment:
        - "HOST=server"

networks:
  grpc:
    name: "grpc"
    driver: "bridge"
